---
name: Docker Image Push to Artifactory
on:
  - workflow_dispatch
jobs:
  first_job:
    name: Pull and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull image
        run: docker pull adoptopenjdk/openjdk11:alpine-jre
      - name: Login to JFrog Artifactory
        run: jfrog rt config
          --url="https://jfrog.teliacompany.io/artifactory/tfpt-managed-base-docker-images/"
          --user="${{ secrets.JFROG_USERNAME }}" --password="${{
          secrets.JFROG_PASSWORD }}"
      - name: Push image to Artifactory
        run: jfrog rt docker-push
          adoptopenjdk/openjdk11:alpine-jre    tfpt-managed-base-docker-images/
