name: Deploy Docker Image to JFROG Artifactory
on: 
  - workflow_dispatch

env:
  JFF_URL: "https://jfrog.teliacompany.io/artifactory/"
  JF_USER: ${{ secrets.JF_USER }}
  JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
  ARTIFACTORY_READER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  ARTIFACTORY_READER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.ARTIFACTORY_READER_USERNAME }}
          password: ${{ env.ARTIFACTORY_READER_TOKEN }}
      - name: Pull Docker image
        run: |
          docker pull nginx:alpine
      - name: Retag Docker image
        run: |
          docker tag nginx:alpine tfpt-managed-base-docker-images/nginx:alpine
      - name: Login to JFROG Artifactory
        run: 
          docker login --username ${JF_USER} --password ${JF_PASSWORD} https://jfrog.teliacompany.io/artifactory/tfpt-managed-base-docker-images/
      
      - name: Push Docker image
        run: |
          docker push tfpt-managed-base-docker-images/nginx:alpine
