---
name: Docker Image Push to Artifactory
on:
  - workflow_dispatch
jobs:
  first_job:
    name: Pull and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull image
        run: docker pull adoptopenjdk/openjdk11:alpine-jre
      - name: Setup JFROG installation
        uses: jfrog/setup-jfrog-cli@v3        
      - name: Fetch jfrog  
        run: jf --version         
        env:
          JF_URL: ${{ secrets.JF_URL }}
    # Basic authentication credentials
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      - name: Push image to Artifactory
        run: jfrog rt docker-push alpine-jre --url https://jfrog.teliacompany.io/tfpt-managed-base-docker-images/ --user "${{ JF_USER }}"  
        #run: jfrog rt docker-push alpine-jre 
