---
name: Docker Image Push to Artifactory
on:
  - workflow_dispatch
jobs:
  first_job:
    name: Pull and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull image
        run: docker pull adoptopenjdk/openjdk11:alpine-jre
      - name: Setup JFROG installation
        uses: jfrog/setup-jfrog-cli@v3        
      - name: Fetch jfrog  
        run: jf --version         
      - name: Login to JFrog  
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.JF_USER }}
          password: ${{ secrets.JF_PASSWORD }}         
          JF_URL: ${{ secrets.JF_URL }}
        run: |
          jf rt ping  
